import React from "react";
import { motion } from "framer-motion";
import SubPageLayout from "@/components/hosting/SubPageLayout";

const sections = [
  {
    title: "1. Acceptance of Terms",
    body: "By accessing or using MadeCraftAI services, you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not access or use our services. These terms constitute a legally binding agreement between you and MadeCraftAI.",
  },
  {
    title: "2. Description of Service",
    body: "MadeCraftAI provides AI-powered website creation, code generation, visual building, and related development tools. Our platform uses machine learning models to assist with site generation, code export, and project management. We strive to maintain high availability but do not guarantee uninterrupted service. We reserve the right to modify, suspend, or discontinue any feature at any time with reasonable notice to affected customers.",
  },
  {
    title: "3. Account Registration",
    body: "You must provide accurate and complete information when creating an account. You are responsible for maintaining the security of your account credentials and for all activities under your account. You must be at least 16 years old to create an account. You agree to notify us immediately of any unauthorized use of your account.",
  },
  {
    title: "4. Acceptable Use Policy",
    body: "You agree not to use our services to generate or distribute illegal content, malware, or spam. Prohibited activities include using AI to create copyrighted material without authorization, generating malicious code, creating deceptive or fraudulent content, violating intellectual property rights, and engaging in any activity that violates applicable laws. Violations may result in immediate suspension without refund.",
  },
  {
    title: "5. AI Credits and Usage",
    body: "Each plan includes a monthly allocation of AI credits that are consumed when generating content, code, or using AI-powered features. Credits do not roll over to the following month. Free plan credits are limited to 30 per month. Paid plans receive their credit allocation on the billing cycle renewal date. Additional credits may be purchased as add-ons where available. Unused credits expire at the end of each billing cycle.",
  },
  {
    title: "6. Payment and Billing",
    body: "Fees are billed in advance on a recurring basis according to your selected billing cycle (monthly or annual). Annual subscribers receive a discount compared to monthly billing. All fees are processed securely through Base44 Payments. We may change pricing with 30 days notice. Failed payments may result in service suspension or downgrade to the Free plan.",
  },
  {
    title: "7. AI-Generated Content",
    body: "Content generated by MadeCraftAI's AI tools is provided for your use within the platform. You retain ownership of projects and content you create. However, due to the nature of AI-generated content, we cannot guarantee that generated output is free from third-party intellectual property claims. You are responsible for reviewing and verifying all AI-generated content before publishing or distributing it.",
  },
  {
    title: "8. Intellectual Property and Copyright",
    body: "All software, AI models, tools, branding, and platform content provided by MadeCraftAI remain our intellectual property. The MadeCraftAI name, logo, and all associated materials are protected by copyright and trademark law. You may not copy, reproduce, distribute, or create derivative works of the platform itself. You retain all rights to the content and data you create on our platform. You grant us a limited license to process your data solely for the purpose of providing and maintaining our services.",
  },
  {
    title: "9. Limitation of Liability",
    body: "MadeCraftAI shall not be liable for any indirect, incidental, special, or consequential damages, including loss of profits, data, or business opportunities arising from AI-generated content or platform usage. Our total liability shall not exceed the amount you paid for our services in the three months preceding the claim. AI-generated output is provided 'as is' without warranty of accuracy, fitness for purpose, or non-infringement.",
  },
  {
    title: "10. Indemnification",
    body: "You agree to indemnify and hold MadeCraftAI harmless from any claims, damages, or expenses arising from your use of our services, your violation of these terms, your use of AI-generated content, or your infringement of third-party rights. We reserve the right to assume exclusive defense of any matter subject to indemnification.",
  },
  {
    title: "11. Termination",
    body: "You may cancel your subscription at any time through your account dashboard. Cancellation takes effect at the end of the current billing cycle. We may terminate or suspend your account immediately if you violate these terms, fail to pay fees, or engage in activities that harm our infrastructure or other users. Upon termination, your data will be deleted within 30 days unless legally restricted.",
  },
  {
    title: "12. Modifications to Terms",
    body: "We may modify these Terms of Service at any time. Material changes will be communicated via email at least 30 days before taking effect. Continued use of our services after the effective date constitutes acceptance of the modified terms.",
  },
  {
    title: "13. Governing Law",
    body: "These terms are governed by the laws of the jurisdiction in which MadeCraftAI is incorporated, without regard to conflict of law principles. Any disputes shall be resolved through binding arbitration, except where prohibited by local consumer protection laws.",
  },
  {
    title: "14. Copyright Notice",
    body: "© 2026 MadeCraftAI. All rights reserved. The MadeCraftAI platform, including all software, AI models, documentation, visual assets, and content, is protected by United States and international copyright laws. Unauthorized reproduction, distribution, or modification of any part of this platform is strictly prohibited and may result in legal action.",
  },
  {
    title: "15. Contact Information",
    body: "For questions about these Terms of Service, please contact us through our contact page. Our legal team is available to address any concerns regarding your use of MadeCraftAI services.",
  },
];

export default function Terms() {
  return (
    <SubPageLayout>
      <div className="max-w-4xl mx-auto px-6 lg:px-8 py-16 lg:py-24">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <p className="font-mono text-xs uppercase tracking-[0.4em] text-[#FFB800] mb-4">
            Legal
          </p>
          <h1 className="font-display text-3xl md:text-5xl font-extrabold text-[#F2F2F2] tracking-tight mb-4">
            TERMS OF SERVICE
          </h1>
          <p className="text-sm text-[#8E9196] font-mono mb-12">
            Last updated: June 2026
          </p>
        </motion.div>

        <div className="space-y-12">
          {sections.map((section, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.03 }}
            >
              <h2 className="font-display text-lg lg:text-xl font-bold text-[#F2F2F2] mb-3">
                {section.title}
              </h2>
              <p className="text-[#8E9196] leading-relaxed text-base lg:text-lg">
                {section.body}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </SubPageLayout>
  );
}